### ISSUE TITLE
Invalid link on the Menpo 3D official website

### ISSUE THREAD

**Issue by Bornblack** [shriyakak/3D-FaceAlignment-in-the-wild#1]
Hi,
I have got the password for the unzip files, but the train dataset download link  on the official website is broken.
Can you share me with a valid dropbox link ?

Invalid link:
https://www.dropbox.com/s/yf8a3btsn8fjdbv/Menpo_3d_challenge_trainset_videos%20%281%29.zip?dl=1

**Comment by Bornblack** [comment]
@shriyakak  
Can you help me ?

**Comment by shriyakak** [comment]
Hi @Bornblack,

I don't have the link anymore, it expired after some time. You can directly reach the dataset's author and raise this concern with them. Please go through this site https://ibug.doc.ic.ac.uk/resources/2nd-facial-landmark-tracking-competition-menpo-ben/
and you can check there the contacts they have given for menpo.

**Comment by Bornblack** [comment]
Hi @shriyakak ,

I try to contact the author but get no response at all.  I only get the password from the Menpo 3D challenge mail. 
Would you mind sharing the zipped annotation file for the 300VW dataset if you still have it ?
My email: black_wang@hust.edu.cn

Thanks!

**Comment by shriyakak** [comment]
Hi @Bornblack, 
No, I'm sorry I don't have that data with me now.

**Comment by Bornblack** [comment]
Thanks any way !
